#!/bin/bash -l

# Set SCC project
#$ -P hasselmogrp

# Set output directory for log files
#$ -o /projectnb/hasselmogrp/Speed' 'Modulation/PYRvsINT/log_Holger
#$ -e /projectnb/hasselmogrp/Speed' 'Modulation/PYRvsINT/err_Holger

# Load required software
module load matlab/2018b

#$ -l h_rt=120:00:00

matlab -nodisplay -r "run_LNmodel_HD_root_SCC('/projectnb/hasselmogrp/hdannenb_1/UnitRecordingData/$1'); exit"
